### PR TITLE
Update card data, add update scripts

### PR DESCRIPTION
**Pull request by jbzdarkid**
I noticed that the data behind this website seems a bit dated, but it looks like the repo is perfectly well-equipped to handle new information.

I wasn't able to actually test the website -- please do that before pushing this data :)

- Refreshed the .json data files with data from 2024
- Added images for the sets from 2024
- Add a python script (and cronjob) to automatically pull and refresh the data, e.g. for nerfs/buffs
  - Note that this script cannot automatically infer new expansions; it will require slight manual updating for new expansion releases. The script should fail automatically (and send an email, if you hae the github action enabled) when that happens.

### CODE REVIEW

**Comment by Evanomnom** [comment]
Hi Joseph. Apologies for missing this, this is great work! Sorry you had to reverse engineer all the card data parsing stuff. As you can guess, I’ve kinda lost interest in this project. I see you created a fork hosted on GitHub pages. If you don’t mind, I may just have cardlegame.com redirect to your link since I’m guessing you’d rather work in there.

**Comment by jbzdarkid** [comment]
Absolutely! I'm also happy to add you as an co-contributor to that team, just in case the interest strikes you again.

**Comment by jbzdarkid** [comment]
If you join the team I believe you'll be able to set up the DNS directly on the github repo -- but give me a sec, I'm going to try and move it so it can live as a root DNS name.

**Comment by jbzdarkid** [comment]
Ok @Evanomnom it should be all set up now. If you join the org and go to https://github.com/cardlegame/cardlegame.github.io/settings/pages it should have steps to set up the DNS name:
image

(if it's easier to just redirect you can do that too)

**Comment by Evanomnom** [comment]
Ok after fiddling with DNS settings I got it working. Thanks again!

**Pull request closed without merging**
